# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ycRHpasaOdi7gtpldWpzw9cHU0MSrjYv
"""

mensagem = 'bem vindo a calculadora'
mensagem = 'por favor insira a operação matemática que deseja.'
mensagem+= '\n+ para adição'
mensagem+= '\n- para subtração'
mensagem+= '\n* para multiplicação'
mensagem+= '\n/ para divisão: '

operação = input(mensagem)

num1 = int(input('insira o primeiro número: '))
num2 = int(input('insira o segundo número: '))
if operação == '+':
    print(f'operação: {num1} {operação} {num2} = {num1 + num2}')
elif operação == '-':
    print(f'operação: {num1} {operação} {num2} = {num1 - num2}')
elif operação == '*':
    print(f'operação: {num1} {operação} {num2} = {num1 * num2}')
elif operação == '/':
        print(f'operação: {num1} {operação} {num2} = {num1 / num2}')
else:
    print('operação inválida')